### ISSUE TITLE
Invalid data format: Invalid passphrase

### ISSUE THREAD

**Issue by MegaBitzCoin** [webchain-network/wallet#155]
``` 
JsonRpcError: Invalid data format: Invalid passphrase
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/MegaBitzCoin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25590:30)
    at new JsonRpcError (file:///C:/Users/MegaBitzCoin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25619:116)
    at file:///C:/Users/MegaBitzCoin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25656:19
 ```

**Comment by MegaBitzCoin** [comment]
help

**Comment by danielwebimp** [comment]
Hello, please can you explain what you did to get this error? In other case, if you were trying to send some coins, then please check your password and try again. That error can be due to wrong password that you entered while sending some coins.
