### ISSUE TITLE
rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S

### ISSUE THREAD

**Issue by frungillo** [webchain-network/wallet#159]
``` 
JsonRpcError: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/frungillo/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25590:30)
    at new JsonRpcError (file:///C:/Users/frungillo/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25619:116)
    at file:///C:/Users/frungillo/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25656:19
 ```

**Comment by danielwebimp** [comment]
Hi, please could you explain how to reproduce that error? And give specifications of the operating system and all necessary details that could help to fix that issue.
