### ISSUE TITLE
Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by randomsymbols** [webchain-network/wallet#179]
``` 
JsonRpcError: Insufficient funds for gas * price + value
    at JsonRpcError.ExtendableBuiltin (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25590:30)
    at new JsonRpcError (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25619:116)
    at file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25656:19
 ```

**Comment by danielwebimp** [comment]
Please make sure you have enough balance to send coins to someone. Default gaz values should be kept unchanged while sending coins.
