### ISSUE TITLE
Invalid address length, expected 40 got 34 bytes

### ISSUE THREAD

**Issue by Pappo93** [webchain-network/wallet#180]
``` 
JsonRpcError: Invalid address length, expected 40 got 34 bytes
    at JsonRpcError.ExtendableBuiltin (file:///Applications/WebchainWallet.app/Contents/Resources/app.asar/app/index.js:25590:30)
    at new JsonRpcError (file:///Applications/WebchainWallet.app/Contents/Resources/app.asar/app/index.js:25619:116)
    at file:///Applications/WebchainWallet.app/Contents/Resources/app.asar/app/index.js:25656:19
 ```

**Comment by cleverrain** [comment]
Hi @Pappo93  please could you give more details of the circumstances? How can we reproduce it? If it's only about the address of your wallet, then make sure you've entered the right wallet and that you are connected to remote node.

**Comment by tendo-abc** [comment]
the wallet address wasn't complete
