### ISSUE TITLE
rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S

### ISSUE THREAD

**Issue by dshmanatov** [webchain-network/wallet#185]
``` 
JsonRpcError: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S
    at JsonRpcError.ExtendableBuiltin (file:///opt/WebchainWallet/resources/app.asar/app/index.js:24551:30)
    at new JsonRpcError (file:///opt/WebchainWallet/resources/app.asar/app/index.js:24580:116)
    at file:///opt/WebchainWallet/resources/app.asar/app/index.js:24617:19
 ```

**Comment by tendo-abc** [comment]
http://i.imgur.com/iFqq8sE.png
