### ISSUE TITLE
Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by mieserfettsack** [webchain-network/wallet#187]
``` 
JsonRpcError: Insufficient funds for gas * price + value
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/Christian/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25590:30)
    at new JsonRpcError (file:///C:/Users/Christian/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25619:116)
    at file:///C:/Users/Christian/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25656:19
 ```

**Comment by mieserfettsack** [comment]
Ah, I see. It was my fault. I calculated wrong. But this should not raise an error like that, imho.
