### ISSUE TITLE
Out of gas

### ISSUE THREAD

**Issue by MAmin233** [webchain-network/wallet#200]
``` 
JsonRpcError: Out of gas
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/amin/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25716:30)
    at new JsonRpcError (file:///C:/Users/amin/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25745:116)
    at file:///C:/Users/amin/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25782:19
 ```

**Comment by danielwebimp** [comment]
Please you don't need to change any setting during your transfer.
