### ISSUE TITLE
Insufficient funds for gas * price + value when choosing MAX amount

### ISSUE THREAD

**Issue by danilo-znamerovszkij** [webchain-network/wallet#206]
``` 
JsonRpcError: Insufficient funds for gas * price + value
    at JsonRpcError.ExtendableBuiltin (file:///Applications/WebchainWallet.app/Contents/Resources/app.asar/app/index.js:25480:30)
    at new JsonRpcError (file:///Applications/WebchainWallet.app/Contents/Resources/app.asar/app/index.js:25509:116)
    at file:///Applications/WebchainWallet.app/Contents/Resources/app.asar/app/index.js:25546:19
 ```

**Comment by danielwebimp** [comment]
@danilo-znamerovszkij Hi, please while proceeding with a transaction of MINTME Coin, don't change default settings of gas : 21000.
