### ISSUE TITLE
Cannot read property 'plus' of null

### ISSUE THREAD

**Issue by JovemNarcas** [webchain-network/wallet#229]
``` 
TypeError: Cannot read property 'plus' of null
    at file:///C:/Users/eu/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:115421:33
    at updateInDeepMap (file:///C:/Users/eu/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4185:22)
    at updateInDeepMap (file:///C:/Users/eu/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4194:23)
    at List.Map.updateIn (file:///C:/Users/eu/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3492:26)
    at List.Map.update (file:///C:/Users/eu/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3484:14)
    at file:///C:/Users/eu/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:115304:23
    at updateInDeepMap (file:///C:/Users/eu/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4185:22)
    at updateInDeepMap (file:///C:/Users/eu/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4194:23)
    at Map.updateIn (file:///C:/Users/eu/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3492:26)
    at Map.update (file:///C:/Users/eu/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3484:14)
 ```

**Comment by danielwebimp** [comment]
@JovemNarcas  Hi, try to reinstall your wallet again.
I encourage you to use instead our new Desktop wallet that you can download from here : https://github.com/mintme-com/wallet/releases , Make sure you have a backup of your wallet, then import it in the new software installed (Desktop wallet).
